#!/bin/bash

# Vercel Environment Variables Setup Script
# Run this to configure your database and admin settings

echo "🔧 Setting up Vercel Environment Variables..."
echo ""
echo "Please go to: https://vercel.com/marwanelachhabs-projects/luxury-perfume-haven/settings/environment-variables"
echo ""
echo "Add these variables for PRODUCTION environment:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable Name: SEED"
echo "Value: true"
echo "Environment: Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable Name: ADMIN_USERNAME"
echo "Value: admin"
echo "Environment: Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable Name: ADMIN_EMAIL"
echo "Value: admin@luxury-perfume-haven.com"
echo "Environment: Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable Name: ADMIN_PASSWORD"
echo "Value: Admin@2025!Secure"
echo "Environment: Production"
echo "⚠️  IMPORTANT: Change this password after first login!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable Name: NODE_ENV"
echo "Value: production"
echo "Environment: Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable Name: JWT_SECRET"
echo "Value: $(openssl rand -base64 32)"
echo "Environment: Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once added, press Enter to redeploy..."
read -p ""
echo ""
echo "🚀 Deploying to Vercel..."
cd /workspaces/luxury-perfume-haven
vercel --prod --yes
